# Generated by Django 3.1.1 on 2020-09-16 17:49

import advito.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ad_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartments', models.TextField(max_length=150)),
                ('vehicles', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='type_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.TextField(max_length=7)),
                ('bay', models.TextField(max_length=7)),
                ('rent', models.TextField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='About')),
                ('avatar', models.ImageField(default=None, upload_to=advito.models.avatar_path)),
                ('sale_ad', models.ManyToManyField(blank=True, related_name='ad', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='model_ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=advito.models.ad_img_path)),
                ('date_pud', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_edit', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.ad_category')),
                ('type_of_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.type_ad')),
            ],
        ),
    ]
