# Generated by Django 3.1.1 on 2020-09-20 12:48

import advito.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to=advito.models.ad_img_path)),
                ('date_pud', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.ad_category')),
                ('in_favor', models.ManyToManyField(blank=True, related_name='favor_ad', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sale_ad',
        ),
        migrations.RemoveField(
            model_name='type_ad',
            name='rent',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_ad',
            field=models.ManyToManyField(blank=True, related_name='My_ad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='model_ad',
        ),
        migrations.AddField(
            model_name='ad',
            name='type_of_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.type_ad'),
        ),
    ]
