# Generated by Django 3.1.1 on 2020-09-23 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='advito_file/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='filters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.filtersadvert', verbose_name='Фильтр'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='views_num',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
