# Generated by Django 3.1.1 on 2020-09-20 16:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('advito', '0002_auto_20200920_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Срок',
                'verbose_name_plural': 'Сроки',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
        migrations.AlterModelOptions(
            name='type_ad',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категори'},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
        migrations.RemoveField(
            model_name='type_ad',
            name='bay',
        ),
        migrations.RemoveField(
            model_name='type_ad',
            name='sales',
        ),
        migrations.AddField(
            model_name='ad',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.gallery', verbose_name='Изображения'),
        ),
        migrations.AddField(
            model_name='ad',
            name='moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, default='12.12.20', max_digits=8, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(default='default_title', max_length=200, unique=True, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='subject',
            field=models.CharField(default='default_title', max_length=1000, verbose_name='Тема обьявления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type_ad',
            name='name',
            field=models.CharField(default='default_title', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type_ad',
            name='slug',
            field=models.SlugField(default='default_title', unique=True, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Текст обьявления'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='type_of_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_ad', to='advito.type_ad'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advito.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='date',
            field=models.ForeignKey(default='12.12.20', on_delete=django.db.models.deletion.CASCADE, to='advito.datead', verbose_name='Срок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.category'),
        ),
        migrations.DeleteModel(
            name='ad_category',
        ),
    ]
