# Generated by Django 3.1.1 on 2020-09-20 16:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0003_auto_20200920_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='advito.datead', verbose_name='Срок'),
        ),
    ]
