# Generated by Django 3.1.1 on 2020-09-20 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0006_auto_20200920_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advito.datead', verbose_name='Срок размещения'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='date_pud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ad',
            name='edit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
