# Generated by Django 3.0.10 on 2020-10-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='views_num',
        ),
    ]
