# Generated by Django 3.0.10 on 2020-10-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0002_remove_advert_views_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='in_favorite',
        ),
        migrations.AddField(
            model_name='advert',
            name='views_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
