# Generated by Django 3.0.10 on 2020-10-14 15:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callboard', '0003_auto_20201014_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='in_favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='advert',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='advito_file/', verbose_name='Файл'),
        ),
    ]
