# Generated by Django 3.0.10 on 2020-10-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0004_auto_20201014_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
