# Generated by Django 3.0.10 on 2020-10-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0005_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='file',
        ),
    ]
