# Generated by Django 3.0.10 on 2020-10-14 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callboard', '0006_remove_advert_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/advito_file/', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('date_publish', models.TimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('in_advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Advert_comments', to='callboard.Advert')),
            ],
        ),
    ]
