# Generated by Django 3.0.10 on 2020-10-26 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0007_auto_20201014_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='in_favorite',
        ),
    ]
