# Generated by Django 3.0.10 on 2020-10-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='comments',
        ),
    ]
