# Generated by Django 3.0.10 on 2020-10-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0002_auto_20201028_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='advito.Advert'),
        ),
    ]
