# Generated by Django 3.0.10 on 2020-10-28 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advito', '0004_auto_20201029_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='favorite',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
