# Generated by Django 3.0.10 on 2020-11-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0005_auto_20201029_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='advito.Advert'),
        ),
    ]
