# Generated by Django 3.0.10 on 2020-11-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0008_advert_in_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='in_post',
            new_name='in_advert',
        ),
    ]
